{
	"version": 1547994162,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/background.png",
		"images/panelmenu-sheet0.png",
		"images/paneltitulo-sheet0.png",
		"images/btnsettings-sheet0.png",
		"images/spawner-sheet0.png",
		"images/banana-sheet0.png",
		"images/slash-sheet0.png",
		"images/splash-sheet0.png",
		"images/splash-sheet1.png",
		"images/corte_banana_baixo-sheet0.png",
		"images/corte_banana_cima-sheet0.png",
		"images/bomba-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/explosao.png",
		"images/melancia-sheet0.png",
		"images/corte_melancia_cima-sheet0.png",
		"images/corte_melancia_baixo-sheet0.png",
		"images/splash_m-sheet0.png",
		"images/splash_m-sheet1.png",
		"images/score_icon-sheet0.png",
		"media/kfine_slice (mp3cut.net).ogg",
		"media/bomb timer sound effect (mp3cut.net).ogg",
		"media/explosion.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}